#!/usr/bin/env python3
"""Render the player-facing campaign dashboard, DW_Dashboard.html.

Normally run automatically: scripts/yamledit.yaml registers this as yamledit's
post-write hook, so every successful edit to a campaign YAML rewrites the page.
It can also be run by hand (see --help-llm).

SECURITY-RELEVANT INVARIANT: this script must never read *_gmsecret.yaml. That
file is rot13'd into the session zip precisely so a player can hold the zip
without spoiling themselves, and this page is the one the player is looking at.
The exclusion happens by filename, before any read - see campaign_documents().

The page is a static template plus one injected JSON blob. All markup, CSS and
JS live in assets/html_templates/dashboard_template.html; this script only turns
YAML into JSON and splices it between two markers. Keeping it that way is what
keeps the invariant above easy to see.
"""

import argparse
import glob
import json
import os
import sys
from datetime import datetime, timezone

HELP_LLM = """\
dashboard.py - render DW_Dashboard.html, the player-facing campaign dashboard.

WHAT IT IS
  One self-contained HTML file: a location header, a tabbed card per player
  character, and a tabbed Basic/Special move reference. Opened in the harness's
  browser/file viewer, it shows the player their sheet and where they are
  without you re-narrating it every turn.

  Move descriptions come from assets/moves.json (rulebook text, generated by
  tools/extract_moves.py). A move name on a sheet that has no entry there still
  appears, marked as having no description - so homebrew moves are visible
  rather than dropped.

YOU USUALLY DO NOT CALL THIS
  scripts/yamledit.yaml registers it as yamledit's post-write hook. Any
  successful `yamledit.pyz` write to a campaign YAML regenerates the page
  automatically. Reads, --get and --dry-run do not. Call it by hand only to
  force a rebuild, to render into a specific path, or to debug.

USAGE
  python3 scripts/dashboard.py [FILE] [--dir PATH] [--out PATH]

  FILE        Optional. The edited YAML path; yamledit appends this. Used only
              to locate the campaign directory. Ignored otherwise.
  --dir PATH  Campaign directory to read. Default: FILE's directory, else CWD.
  --out PATH  Exact output file. Overrides all output-location logic below.
  --quiet     Suppress the success line on stdout (errors still go to stderr).

WHERE IT WRITES (when --out is not given)
  Probes for a sandbox output directory, first match wins:
      /mnt/user-data/outputs/     (Anthropic)
      /mnt/data/                  (OpenAI)
      /home/workdir/artifacts/    (xAI)
  If none exists (Claude Code, plain shells), writes into the campaign
  directory. Filename is always DW_Dashboard.html. If more than one sandbox
  directory exists it errors rather than guess.

WHAT IT READS
  Every *.yaml in the campaign directory, except:
    *_gmsecret.yaml   NEVER opened. Spoiler material; the page is player-facing.
  Of the rest:
    *_environment.yaml   the location header (what the party PERCEIVES).
                         `site_label` renames "Site" in the header, so a
                         settlement reads "Town: Cowsburg".
    anything with `name` + `class`   a player character card.
  Absent keys render empty. A half-filled sheet mid-creation still produces a
  page, and a missing environment file is not an error.

EXIT CODES
  0 wrote the page.   1 could not (no template, unwritable path, ambiguous
  sandbox). As a hook, a non-zero exit only warns on stderr - it never fails
  the yamledit write that triggered it.

TURNING IT OFF
  YAMLEDIT_NO_HOOK=1 for one call, or `hook: {enabled: false}` in
  scripts/yamledit.yaml permanently.

IF THE PAGE STOPS UPDATING
  The hook command names `python3`. Where that is not on PATH (some Windows
  setups) yamledit warns to stderr and edits keep working while the page goes
  stale. Fix: change `python3` to `python` in scripts/yamledit.yaml.

REMINDERS
  - Keep <slug>_environment.yaml current as the party moves; it is the only
    source for the location header, and editing it fires this hook.
  - Never copy gmsecret content into the environment file. It is player-visible.
  - On mobile the page is invisible until presented once per session. Present it
    after the campaign files exist, and again if the player says they can't see it.
"""

MARKER_START = "<!--DW-DATA-START-->"
MARKER_END = "<!--DW-DATA-END-->"

OUTPUT_NAME = "DW_Dashboard.html"

# One per provider; only one ever exists in a given sandbox.
SANDBOX_OUTPUT_DIRS = (
    "/mnt/user-data/outputs",   # Anthropic
    "/mnt/data",                # OpenAI
    "/home/workdir/artifacts",  # xAI
)

TEMPLATE_RELPATH = os.path.join("assets", "html_templates", "dashboard_template.html")
MOVES_RELPATH = os.path.join("assets", "moves.json")

GMSECRET_SUFFIX = "_gmsecret.yaml"
ENVIRONMENT_SUFFIX = "_environment.yaml"


def load_yaml_reader():
    """Borrow ruamel.yaml from the vendored zipapp, as validate_skill.py does."""
    pyz = os.path.join(os.path.dirname(os.path.abspath(__file__)), "yamledit.pyz")
    if os.path.isfile(pyz):
        sys.path.insert(0, pyz)
    import ruamel.yaml

    return ruamel.yaml.YAML(typ="safe")


def plain(value):
    """Convert ruamel's mapping/sequence types into plain JSON-able Python."""
    if isinstance(value, dict):
        return {str(k): plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [plain(v) for v in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def campaign_documents(reader, directory):
    """Return (environment, characters) read from *.yaml in `directory`.

    *_gmsecret.yaml is excluded by filename before anything is opened. Mirrors
    the same exclusion in session_save.py. Do not replace this with a
    content-based test: the point is that the file is never read at all.
    """
    environment = None
    characters = []

    for path in sorted(glob.glob(os.path.join(directory, "*.yaml"))):
        base = os.path.basename(path)
        if base.endswith(GMSECRET_SUFFIX):
            continue

        try:
            with open(path, "r", encoding="utf-8") as handle:
                doc = plain(reader.load(handle))
        except Exception as exc:  # a broken sheet must not blank the whole page
            print("dashboard: skipping {} ({})".format(base, exc), file=sys.stderr)
            continue

        if not isinstance(doc, dict):
            continue

        if base.endswith(ENVIRONMENT_SUFFIX):
            environment = doc
        elif "name" in doc and "class" in doc:
            doc["_file"] = base
            characters.append(doc)

    characters.sort(key=lambda c: str(c.get("name") or c.get("_file") or "").lower())
    return environment, characters


def load_moves(skill_dir):
    """Load assets/moves.json (rulebook move text). Missing is not fatal.

    Generated by tools/extract_moves.py from the vendored rulebook XML. If it is
    absent the page simply lists move names without descriptions, which is what
    the sheets themselves carry.
    """
    path = os.path.join(skill_dir, MOVES_RELPATH)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError) as exc:
        print("dashboard: no move descriptions ({})".format(exc), file=sys.stderr)
        return {"basic": [], "special": [], "classes": {}}


def resolve_moves(names, character_class, moves_data):
    """Pair each move name on a sheet with its rulebook text.

    The sheet is authoritative about *which* moves a character has - this only
    supplies descriptions. A name with no match still appears, so a homebrew or
    misspelled move is visible on the page rather than silently dropped.
    """
    if not isinstance(names, list):
        return []

    classes = moves_data.get("classes") or {}
    lookup = {}

    def absorb(entries):
        for entry in entries or []:
            key = str(entry.get("name", "")).strip().lower()
            if key and key not in lookup:
                lookup[key] = entry.get("blocks") or []

    # The character's own class first, so a name shared between two classes
    # resolves to the right text.
    own = classes.get(str(character_class or "").strip().title())
    if own:
        absorb(own.get("starting"))
        absorb(own.get("advanced"))
    for other in classes.values():
        if other is not own:
            absorb(other.get("starting"))
            absorb(other.get("advanced"))
    absorb(moves_data.get("basic"))
    absorb(moves_data.get("special"))

    resolved = []
    for name in names:
        if isinstance(name, dict):
            name = name.get("name", "")
        name = str(name).strip()
        if not name:
            continue
        resolved.append({"name": name, "blocks": lookup.get(name.lower(), [])})
    return resolved


def encode_payload(payload):
    """Serialize to JSON that is safe to sit inside a <script> element.

    ensure_ascii keeps the bytes plain; escaping <, > and & means a character
    note containing "</script>" cannot break out of the carrier. This is the
    ONLY path by which a campaign value reaches the page - one data path, one
    escaping rule. The template's JS must build DOM with textContent for that
    to be worth anything.
    """
    blob = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    return blob.replace("&", "\\u0026").replace("<", "\\u003c").replace(">", "\\u003e")


def splice(template, encoded):
    start = template.find(MARKER_START)
    end = template.find(MARKER_END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            "template is missing the {} / {} marker pair".format(MARKER_START, MARKER_END)
        )
    head = template[: start + len(MARKER_START)]
    tail = template[end:]
    return head + encoded + tail


def resolve_output(explicit, campaign_dir):
    if explicit:
        return os.path.abspath(explicit)

    found = [d for d in SANDBOX_OUTPUT_DIRS if os.path.isdir(d)]
    if len(found) > 1:
        raise ValueError(
            "several sandbox output directories exist ({}); pass --out to say which "
            "to use".format(", ".join(found))
        )
    target_dir = found[0] if found else campaign_dir
    return os.path.abspath(os.path.join(target_dir, OUTPUT_NAME))


def main():
    if "--help-llm" in sys.argv[1:]:
        sys.stdout.write(HELP_LLM)
        return 0

    ap = argparse.ArgumentParser(
        description="Render the player-facing campaign dashboard, DW_Dashboard.html."
    )
    ap.add_argument("file", nargs="?",
                    help="the edited YAML path (yamledit appends this); used only to "
                         "locate the campaign directory")
    ap.add_argument("--dir", dest="directory",
                    help="campaign directory to read (default: FILE's directory, else CWD)")
    ap.add_argument("--out", help="exact output path; overrides the output-location probe")
    ap.add_argument("--quiet", action="store_true", help="suppress the success line")
    ap.add_argument("--help-llm", action="store_true", dest="help_llm",
                    help="print the dense full reference written for LLM callers, then exit")
    args = ap.parse_args()

    if args.directory:
        campaign_dir = os.path.abspath(args.directory)
    elif args.file:
        campaign_dir = os.path.dirname(os.path.abspath(args.file)) or os.getcwd()
    else:
        campaign_dir = os.getcwd()

    skill_dir = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    )
    template_path = os.path.join(skill_dir, TEMPLATE_RELPATH)

    try:
        with open(template_path, "r", encoding="utf-8") as handle:
            template = handle.read()
    except OSError as exc:
        print("dashboard: cannot read template {} ({})".format(template_path, exc),
              file=sys.stderr)
        return 1

    reader = load_yaml_reader()
    environment, characters = campaign_documents(reader, campaign_dir)

    moves_data = load_moves(skill_dir)
    for character in characters:
        sheet_moves = character.get("moves") or {}
        if not isinstance(sheet_moves, dict):
            sheet_moves = {}
        character["move_details"] = {
            "starting": resolve_moves(
                sheet_moves.get("starting"), character.get("class"), moves_data),
            "advanced": resolve_moves(
                sheet_moves.get("advanced"), character.get("class"), moves_data),
        }

    payload = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "environment": environment,
        "characters": characters,
        # Always present: the basic/special move reference is the same for every
        # campaign and is what the player actually reaches for mid-turn.
        "reference": {
            "basic": moves_data.get("basic") or [],
            "special": moves_data.get("special") or [],
        },
    }

    try:
        page = splice(template, encode_payload(payload))
        destination = resolve_output(args.out, campaign_dir)
    except ValueError as exc:
        print("dashboard: {}".format(exc), file=sys.stderr)
        return 1

    try:
        parent = os.path.dirname(destination)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(destination, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(page)
    except OSError as exc:
        print("dashboard: cannot write {} ({})".format(destination, exc), file=sys.stderr)
        return 1

    if not args.quiet:
        # Reached mid-session, when the model has long forgotten this script's
        # options - so say what got in and what to do when it looks wrong.
        print("dashboard: wrote {} ({} character sheet(s), location {})".format(
            destination,
            len(characters),
            "set" if environment and environment.get("where") else "unset",
        ))
        if environment is None:
            print("  no *_environment.yaml in {} - create one from "
                  "assets/yaml_templates/environment_template.yaml so the header "
                  "shows where the party is".format(campaign_dir))
        print("  present this file to the player once per session, or when they say "
              "they can't see it")

    return 0


if __name__ == "__main__":
    sys.exit(main())
